### ISSUE TITLE
Create Mac (Homebrew/MacPorts) packages

### ISSUE THREAD

**Issue by mellowcandle** [mellowcandle/bitwise#5] opened 2019-05-07 15:56 UTC

**Comment by herrbischoff** [comment] 2019-07-11 13:15
Regarding this, there are compile errors when building on macOS (without Homebrew though):

./configure:
```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking for gcc option to accept ISO C99... (cached) none needed
checking for form_driver in -lform... yes
checking for newwin in -lncurses... yes
checking for rl_bind_key in -lreadline... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking curses.h usability... yes
checking curses.h presence... yes
checking for curses.h... yes
checking form.h usability... yes
checking form.h presence... yes
checking for form.h... yes
checking readline/history.h usability... yes
checking readline/history.h presence... yes
checking for readline/history.h... yes
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for uint64_t... yes
checking for working strcoll... yes
checking for memchr... yes
checking for memmove... yes
checking for memset... yes
checking for stpcpy... yes
checking for strchr... yes
checking for strcspn... yes
checking for strdup... yes
checking for strerror... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating inc/config.h
config.status: inc/config.h is unchanged
config.status: executing depfiles commands
```

make:
```
depbase=`echo src/main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I./inc       -g -O2 -MT src/main.o -MD -MP -MF $depbase.Tpo -c -o src/main.o src/main.c &&\
	mv -f $depbase.Tpo $depbase.Po
src/main.c:24:56: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
        printf("%sDecimal: %s%lu\n", color_green, color_blue, val);
                             ~~~                              ^~~
                             %llu
src/main.c:25:61: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
        printf("%sHexdecimal: %s0x%lX\n", color_green, color_blue, val);
                                  ~~~                              ^~~
                                  %llX
src/main.c:26:55: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
        printf("%sOctal: %s0%lo\n", color_green, color_blue, val);
                            ~~~                              ^~~
                            %llo
3 warnings generated.
depbase=`echo src/misc.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I./inc       -g -O2 -MT src/misc.o -MD -MP -MF $depbase.Tpo -c -o src/misc.o src/misc.c &&\
	mv -f $depbase.Tpo $depbase.Po
src/misc.c:242:36: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
                        ret = sprintf(buf, "%lu bytes", val);
                                            ~~~         ^~~
                                            %llu
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
src/misc.c:255:36: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
                        ret = sprintf(buf, "%lu bytes", val);
                                            ~~~         ^~~
                                            %llu
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
2 warnings generated.
depbase=`echo src/interactive.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I./inc       -g -O2 -MT src/interactive.o -MD -MP -MF $depbase.Tpo -c -o src/interactive.o src/interactive.c &&\
	mv -f $depbase.Tpo $depbase.Po
src/interactive.c:599:4: warning: implicit declaration of function 'rl_resize_terminal' is invalid in C99 [-Wimplicit-function-declaration]
                        rl_resize_terminal();
                        ^
1 warning generated.
depbase=`echo src/cmd.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I./inc       -g -O2 -MT src/cmd.o -MD -MP -MF $depbase.Tpo -c -o src/cmd.o src/cmd.c &&\
	mv -f $depbase.Tpo $depbase.Po
src/cmd.c:82:8: warning: implicitly declaring library function 'isspace' with type 'int (int)' [-Wimplicit-function-declaration]
                if (!isspace(string[i]))
                     ^
src/cmd.c:82:8: note: include the header <ctype.h> or explicitly provide a declaration for 'isspace'
src/cmd.c:137:36: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
                        sprintf(result_string, "0x%lx", result);
                                                  ~~~   ^~~~~~
                                                  %llx
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
src/cmd.c:192:35: error: use of undeclared identifier 'rl_display_prompt'; did you mean 'rl_set_prompt'?
        mvwprintw(cmd_win, 0, 0, "%s%s", rl_display_prompt, rl_line_buffer);
                                         ^~~~~~~~~~~~~~~~~
                                         rl_set_prompt
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/readline/readline.h:204:7: note: 'rl_set_prompt' declared here
int              rl_set_prompt(const char *);
                 ^
src/cmd.c:200:2: error: use of undeclared identifier 'rl_catch_signals'
        rl_catch_signals = 0;
        ^
src/cmd.c:201:2: error: use of undeclared identifier 'rl_catch_sigwinch'
        rl_catch_sigwinch = 0;
        ^
src/cmd.c:204:2: error: use of undeclared identifier 'rl_change_environment'
        rl_change_environment = 0;
        ^
src/cmd.c:206:2: error: use of undeclared identifier 'rl_input_available_hook'
        rl_input_available_hook = readline_input_avail;
        ^
2 warnings and 5 errors generated.
make: *** [src/cmd.o] Error 1
```

**Comment by mellowcandle** [comment] 2019-07-11 13:20
Interesting, the warnings can be easily fixed, but the readline is suspicious.
These are exports from the libreadline, It's very peculiar they're missing in Mac OS.

Can you check which version of libreadline you have ?

**Comment by herrbischoff** [comment] 2019-07-11 13:30
Here you go:

```
$ cat /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/readline/readline.h
/*      $NetBSD: readline.h,v 1.33 2012/05/15 17:30:04 christos Exp $   */
[...]
```

**Comment by mellowcandle** [comment] 2019-07-11 13:57
Yes, it appears like that.
See here:
https://github.com/jonas/tig/issues/185

Besides that, I fixed the other warnings in master.
Try to see if you can upgrade it.

**Comment by herrbischoff** [comment] 2019-07-11 18:39
I have checked out master and compiled again. Here's the make output:

```
depbase=`echo src/main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        gcc -DHAVE_CONFIG_H -I. -I./inc       -g -O2 -MT src/main.o -MD -MP -MF $depbase.Tpo -c -o src/main.o src/main.c &&\
        mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/misc.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        gcc -DHAVE_CONFIG_H -I. -I./inc       -g -O2 -MT src/misc.o -MD -MP -MF $depbase.Tpo -c -o src/misc.o src/misc.c &&\
        mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/interactive.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        gcc -DHAVE_CONFIG_H -I. -I./inc       -g -O2 -MT src/interactive.o -MD -MP -MF $depbase.Tpo -c -o src/interactive.o src/interactive.c &&\
        mv -f $depbase.Tpo $depbase.Po
src/interactive.c:599:4: warning: implicit declaration of function 'rl_resize_terminal' is invalid in C99 [-Wimplicit-function-declaration]
                        rl_resize_terminal();
                        ^
1 warning generated.
depbase=`echo src/cmd.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        gcc -DHAVE_CONFIG_H -I. -I./inc       -g -O2 -MT src/cmd.o -MD -MP -MF $depbase.Tpo -c -o src/cmd.o src/cmd.c &&\
        mv -f $depbase.Tpo $depbase.Po
src/cmd.c:138:36: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
                        sprintf(result_string, "0x%lx", result);
                                                  ~~~   ^~~~~~
                                                  %llx
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
src/cmd.c:193:35: error: use of undeclared identifier 'rl_display_prompt'; did you mean 'rl_set_prompt'?
        mvwprintw(cmd_win, 0, 0, "%s%s", rl_display_prompt, rl_line_buffer);
                                         ^~~~~~~~~~~~~~~~~
                                         rl_set_prompt
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/readline/readline.h:204:7: note: 'rl_set_prompt' declared here
int              rl_set_prompt(const char *);
                 ^
src/cmd.c:201:2: error: use of undeclared identifier 'rl_catch_signals'
        rl_catch_signals = 0;
        ^
src/cmd.c:202:2: error: use of undeclared identifier 'rl_catch_sigwinch'
        rl_catch_sigwinch = 0;
        ^
src/cmd.c:205:2: error: use of undeclared identifier 'rl_change_environment'
        rl_change_environment = 0;
        ^
src/cmd.c:207:2: error: use of undeclared identifier 'rl_input_available_hook'
        rl_input_available_hook = readline_input_avail;
        ^
1 warning and 5 errors generated.
make: *** [src/cmd.o] Error 1
```

However, I have created a [MacPorts](https://www.macports.org) submission that builds just fine when you supply the port system's own readline: https://github.com/macports/macports-ports/pull/4802

It's not Homebrew but it's an arguably cleaner alternative.

**Comment by mellowcandle** [comment] 2019-07-11 18:48
This is awesome.
So basically we just wait for the macports pull request to merge and update our readme. right ?

I don't own a mac, but I managed to get travis to build on mac, but it fails with the same error you have.
There's something weird with the libreadline in mac

**Comment by herrbischoff** [comment] 2019-07-11 19:13
That's right. It shouldn't take long for someone to come along and create the Homebrew formula. I use MacPorts exclusively now so I cannot do it.

**Comment by frklan** [comment] 2019-07-14 15:29
Hi, I got the same error trying to compile for macOS, installing readline via homebrew gives this hint:
```
[...]
==> Caveats
readline is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

For compilers to find readline you may need to set:
  export LDFLAGS="-L/usr/local/opt/readline/lib"
  export CPPFLAGS="-I/usr/local/opt/readline/include"
[...]
````
setting those exports and rerunning ```./configure``` and ```make``` it compiles without any error.

**Comment by mellowcandle** [comment] 2019-07-14 15:32
Very interesting, I don't own a mac, so I can't debug this efficiently, but this looks very promising.
I'll try to see if it assists.

**Comment by insightjuan** [comment] 2019-07-15 04:54
I just tried compiling in a homebrew environment using the LDFLAGS and CPPFLAGS mentioned by @frklan. It does compile with no warnings, but I can't run any calculations either in the interactive mode (:) or via the command line:

**Comment by mellowcandle** [comment] 2019-07-15 06:39
hmmm, interesting.

**Comment by mellowcandle** [comment] 2019-07-15 06:40
can you build again, but this time add - - enable-tracing to configure?

**Comment by mellowcandle** [comment] 2019-07-15 06:41
run the interactive mode and writes some characters, afterwards exit and upload the file log.txt

**Comment by mellowcandle** [comment] 2019-07-15 06:41
I suspect it might be related to wide characters being sent in Mac.

**Comment by insightjuan** [comment] 2019-07-15 12:24
Threw me there for a sec with --enable-tracing, it's --enable-trace. When you turn that on, the compile does spit out a couple of warnings:

`src/interactive.c:243:21: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
        LOG("Val = %lu\n", g_val);
                   ~~~     ^~~~~
                   %llu
./inc/bitwise.h:61:30: note: expanded from macro 'LOG'
#define LOG(...) fprintf(fd, __VA_ARGS__);fflush(fd)`

Here's the log file you requested

[log.txt](https://github.com/mellowcandle/bitwise/files/3392229/log.txt)

**Comment by mellowcandle** [comment] 2019-07-15 12:49
Thanks.
sorry for the type, I typed from my phone.
Anyway, I looked at the log, looks like the inputs are processed correctly,
So, I'm a bit puzzled, how can it occur in command line mode, it's just
printf to the screen.
Can you explain exactly what happens when your run command line mode like
this:
```
./bitwise 0x1234
```

**Comment by insightjuan** [comment] 2019-07-15 12:52
You get this:

'[juan:~/bitwise-master]$ ./bitwise 0x1234
Couldn't parse expression: 0x1234
Usage: bitwise [OPTION...] [expression]

[expression] mathematical expression

  -i, --interactive	 Load interactive mode (default if no input)
  -w, --width[b|w|l|d]	 Set bit width (default: l)
  -h, --help		 Display this help and exit
  -v, --version		 Output version information and exit
  -s, --si		 Print size acoording to SI standard. (default: IEC standard)
      --no-color	 Start without color support

'[juan:~/bitwise-master]$ ./bitwise 0x1234
Couldn't parse expression: 0x1234
Usage: bitwise [OPTION...] [expression]

[expression] mathematical expression

  -i, --interactive	 Load interactive mode (default if no input)
  -w, --width[b|w|l|d]	 Set bit width (default: l)
  -h, --help		 Display this help and exit
  -v, --version		 Output version information and exit
  -s, --si		 Print size acoording to SI standard. (default: IEC standard)
      --no-color	 Start without color support

'


Which incidentally, reminds me - you have a typo in the help you print out "acooding" instead of "according" in the -s option

**Comment by mellowcandle** [comment] 2019-07-15 12:58
Hi,
First thanks for your time, I don't have a mac and the port is ongoing
effort.
I will try to write some unit-tests and check them in Travis CI to fix the
problem.
Thanks,
Ramon.

**Comment by herrbischoff** [comment] 2019-07-15 13:21
Just a heads up: I'm running into the same issues outlined above.

**Comment by frklan** [comment] 2019-07-15 19:12
Hi, hmm this is interesting I'm getting the same error as @insightjuan!

I recompiled the code with debugging symbols and I've spent a bit tracing the error, I'm launching the program like so "./bitwise 0x1234".

After a while, I end up in the function ```Token *tokenize(const char *expression)``` (in src/shunting-yard.c); correct me if I'm wrong here but I believe that the while loop starting on line 141 should run 6 iterations and line 156 should evaluate to true, right? This does not happen and token.type is not set to TOKEN_NUMBER, the method returns 0 and we'll get the error ```Couldn't parse expression: 0x1234```.

I'm not quite sure why, but the macos version of sscanf does not seem to like the %m format specifier.

**Comment by mellowcandle** [comment] 2019-07-15 19:17
nice. I think you nailed it...
you saved me a lot of trouble of debugging through Travis.

the only thing missing is a pull request :)

**Comment by mellowcandle** [comment] 2019-07-15 20:44
@frklan nice job.let me know if you want to fix it. I can fix it tomorrow.
just remove the %m and allocate memory ourselves.

**Comment by frklan** [comment] 2019-07-16 04:04
> @frklan nice job.let me know if you want to fix it. I can fix it tomorrow.
> just remove the %m and allocate memory ourselves.

Thanks! 

I'm not sure I know how to the the allocation properly. I tried changing line 152 to ````Token token = {TOKEN_UNKNOWN, malloc(sizeof(expression))};````and then call free on the tooken.value after ````c += token.value ? strlen(token.value) : 1;````; now I get a ````bitwise(79141,0x7fffb2a223c0) malloc: *** error for object 0x7ff9d3d00260: pointer being freed was not allocated````error when running. I'n no good at pointers 😢

**Comment by mellowcandle** [comment] 2019-07-16 04:20
@frklan it's a bir tricky. 
the error you got is from free that occur afterwards. the function shouldn't free anything, only allocate. 
it involves completely rewriting the allocation in the function. 
I'll work on it today.

**Comment by mellowcandle** [comment] 2019-07-16 14:38
@frklan @herrbischoff  @insightjuan 
Fixed: c4131c92f8ea9188b18ecf3b106ca0b1248e4e3c
Thanks for @frklan on the analysis.

Let me know if it works good now on mac. also, MAC builds are not enabled by default in Travis.

**Comment by frklan** [comment] 2019-07-16 14:54
> @frklan @herrbischoff @insightjuan
> Fixed: [c4131c9](https://github.com/mellowcandle/bitwise/commit/c4131c92f8ea9188b18ecf3b106ca0b1248e4e3c)
> Thanks for @frklan on the analysis.
> 
> Let me know if it works good now on mac. also, MAC builds are not enabled by default in Travis.

Seems to be working as it should 🎉! Thanks for fixing it.

**Comment by mellowcandle** [comment] 2019-07-16 15:27
@frklan excellent. I'll draft, a new version.

**Comment by insightjuan** [comment] 2019-07-16 16:12
FWIW, I concur that the new version works on Mac with homebrew.  I needed to install:

`brew install readline autoconf automake`

and also do:
`
export LDFLAGS="-L/usr/local/opt/readline/lib"
export CPPFLAGS="-I/usr/local/opt/readline/include"
`

before you can run `./bootstrap.sh'

once you have that, it builds and runs correctly.

**Comment by mellowcandle** [comment] 2019-07-16 16:29
@insightjuan You might want to update your macports pull request to point to v0.32 for the package to actually work :)

**Comment by insightjuan** [comment] 2019-07-16 16:32
@mellowcandle that's assuming I'm using macports :-). I know - Mac's can be awesome and frustrating sometimes. 

FWIW - macports and homebrew are competing package managers. Getting this loaded up on one doesn't imply it's available on the other. I've never written up a package for homebrew (my preferred package manager) or I would do it for the team.

**Comment by mellowcandle** [comment] 2019-07-16 16:41
@insightjuan 
Forgive me, I miss tagged you, @herrbischoff already started macport submission.
But you're more the welcome to assist with homebrew package. :)

**Comment by herrbischoff** [comment] 2019-07-17 10:56
@mellowcandle: Confirmed working on my end. Working version updated in MacPorts PR. It only needs to run all test successfully and be merged.

**Comment by kavu** [comment] 2019-07-21 19:00
Speaking of Homebrew. I've just created new PR to Homebrew Core formulas https://github.com/Homebrew/homebrew-core/pull/42257

Can somebody who prefer Homebrew to try it out too, check if it works for them? Thanks!

**Comment by mellowcandle** [comment] 2019-07-21 20:17
@herrbischoff 
Hey, looks like MacPorts PR was merged. can you please write a small line on how to install it on the Readme page ?

Thanks !

**Comment by mellowcandle** [comment] 2019-07-21 20:36
@kavu 
> Speaking of Homebrew. I've just created new PR to Homebrew Core formulas [Homebrew/homebrew-core#42257](https://github.com/Homebrew/homebrew-core/pull/42257)
> 
> Can somebody who prefer Homebrew to try it out too, check if it works for them? Thanks!
Hey. Awesome.
Thanks.
Regarding the PR. I briefly looked and I see  ncurses dependency is missing. is it on purpose ?
Also, how can you ensure that _homebrew_ libreadline is used and not OSX libedit ?
Thanks for this.
Ramon.

**Comment by kavu** [comment] 2019-07-21 20:43
@mellowcandle 	

Yeah, I though about `ncurses` at last moment too. But it works perfectly without it, because it links to macOS system `ncurses`:

```
% otool -L /usr/local/bin/bitwise
/usr/local/bin/bitwise:
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libform.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/local/opt/readline/lib/libreadline.8.dylib (compatibility version 8.0.0, current version 8.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
``` 

And about `readline`. I guess it is Homrbrew magic. At first I configured build with `CFLAGS` and `LDFLAGS`, set to `readline` paths we depend on. But now I had removed those flags and it still builds and works properly, on my macOS and Homebrew's CI too. Magic!

**Comment by herrbischoff** [comment] 2019-07-23 17:07
> @herrbischoff
> Hey, looks like MacPorts PR was merged. can you please write a small line on how to install it on the Readme page ?
> 
> Thanks !

Here you go: https://github.com/mellowcandle/bitwise/pull/31 😉

**Closed** 2019-08-09 11:24 UTC
Labels: enhancement, good first issue, help wanted
